software_groups: &software
  - "base"

jobs:
  etcd:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    start_in: "etcd"
    packages:
      - type: debian
        name: etcd
        depends:
          - runit-common
          - uuid
        repos:
          - mxm
        target: install
