#!/bin/bash
set -e

exec 2>&1

DEFAULTS=/etc/default/etcd

if [[ -f ${DEFAULTS} ]]
then
  source $DEFAULTS
fi

mac="$(curl http://169.254.169.254/latest/meta-data/mac)"
internal_ip="$(curl http://169.254.169.254/latest/meta-data/network/interfaces/macs/${mac}/local-ipv4s)"

ETCD_ADDR="${internal_ip}:4001"
ETCD_PEER_ADDR="${internal_ip}:7001"

eval $(sed -e "s/^/export /" /etc/environment)

exec chpst -u etcd etcd -data-dir /var/lib/etcd -name ${ETCD_NAME} -discovery ${ETCD_DISCOVERY_URL} -peer-addr ${ETCD_PEER_ADDR} -addr ${ETCD_ADDR}
